<?php

namespace ContainerMV70dLz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_YvAD4VJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.yvAD4VJ' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/src/MessageHandler/TestHandler.php';

        return $container->privates['.messenger.handler_descriptor.yvAD4VJ'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\MessageHandler\TestHandler(($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container))), []);
    }
}
