<?php

namespace ContainerMV70dLz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandChoiceTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Dukecity\CommandSchedulerBundle\Form\Type\CommandChoiceType' shared autowired service.
     *
     * @return \Dukecity\CommandSchedulerBundle\Form\Type\CommandChoiceType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/dukecity/command-scheduler-bundle/Form/Type/CommandChoiceType.php';

        return $container->services['Dukecity\\CommandSchedulerBundle\\Form\\Type\\CommandChoiceType'] = new \Dukecity\CommandSchedulerBundle\Form\Type\CommandChoiceType(($container->services['Dukecity\\CommandSchedulerBundle\\Service\\CommandParser'] ?? $container->load('getCommandParserService')));
    }
}
