<?php

namespace ContainerMV70dLz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocumentControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Wu_EQzd.App\Controller\DocumentController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Wu_EQzd.App\\Controller\\DocumentController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'document' => ['privates', '.errored..service_locator.Wu_EQzd.App\\Entity\\Document', NULL, 'Cannot autowire service ".service_locator.Wu_EQzd": it needs an instance of "App\\Entity\\Document" but this type has been excluded in "config/services.yaml".'],
        ], [
            'document' => 'App\\Entity\\Document',
        ]))->withContext('App\\Controller\\DocumentController::show()', $container);
    }
}
