<?php

namespace ContainerMV70dLz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDisableCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.Dukecity\CommandSchedulerBundle\Command\DisableCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.Dukecity\\CommandSchedulerBundle\\Command\\DisableCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('scheduler:disable', [], 'Command to disable one or all scheduled commands', false, #[\Closure(name: 'Dukecity\\CommandSchedulerBundle\\Command\\DisableCommand')] fn (): \Dukecity\CommandSchedulerBundle\Command\DisableCommand => ($container->services['Dukecity\\CommandSchedulerBundle\\Command\\DisableCommand'] ?? $container->load('getDisableCommandService')));
    }
}
