<?php

namespace ContainerMV70dLz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDisableCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Dukecity\CommandSchedulerBundle\Command\DisableCommand' shared autowired service.
     *
     * @return \Dukecity\CommandSchedulerBundle\Command\DisableCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/dukecity/command-scheduler-bundle/Command/DisableCommand.php';

        $container->services['Dukecity\\CommandSchedulerBundle\\Command\\DisableCommand'] = $instance = new \Dukecity\CommandSchedulerBundle\Command\DisableCommand(($container->services['doctrine'] ?? self::getDoctrineService($container)), 'default');

        $instance->setName('scheduler:disable');
        $instance->setDescription('Command to disable one or all scheduled commands');

        return $instance;
    }
}
