<?php

namespace ContainerMV70dLz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetRssControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\GetRssController' shared autowired service.
     *
     * @return \App\Controller\GetRssController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/GetRssController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/RssService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/XmlReader.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));
        $b = ($container->privates['App\\Repository\\DocumentRepository'] ?? $container->load('getDocumentRepositoryService'));

        $container->services['App\\Controller\\GetRssController'] = $instance = new \App\Controller\GetRssController(new \App\Service\RssService($container->parameters['site_urls'], $a, $b), ($container->services['App\\Service\\XmlReader'] ??= new \App\Service\XmlReader()), $a, $b);

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\GetRssController', $container));

        return $instance;
    }
}
