<?php

namespace ContainerMV70dLz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScheduledCommandsetCreatedAtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d9q2ffH.Dukecity\CommandSchedulerBundle\Entity\ScheduledCommand::setCreatedAt()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d9q2ffH.Dukecity\\CommandSchedulerBundle\\Entity\\ScheduledCommand::setCreatedAt()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'createdAt' => ['privates', '.errored..service_locator.d9q2ffH.DateTime', NULL, 'Cannot autowire service ".service_locator.d9q2ffH": it references class "DateTime" but no such service exists.'],
        ], [
            'createdAt' => 'DateTime',
        ]))->withContext('Dukecity\\CommandSchedulerBundle\\Entity\\ScheduledCommand::setCreatedAt()', $container);
    }
}
