<?php

namespace ContainerMV70dLz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScheduledCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Dukecity\CommandSchedulerBundle\Entity\ScheduledCommand' shared autowired service.
     *
     * @return \Dukecity\CommandSchedulerBundle\Entity\ScheduledCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/dukecity/command-scheduler-bundle/Entity/ScheduledCommand.php';

        return $container->services['Dukecity\\CommandSchedulerBundle\\Entity\\ScheduledCommand'] = new \Dukecity\CommandSchedulerBundle\Entity\ScheduledCommand();
    }
}
