<?php

namespace ContainerMV70dLz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSourceControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WDauLPg.App\Controller\SourceController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.WDauLPg'] ?? $container->load('get_ServiceLocator_WDauLPgService'));

        if (isset($container->privates['.service_locator.WDauLPg.App\\Controller\\SourceController::edit()'])) {
            return $container->privates['.service_locator.WDauLPg.App\\Controller\\SourceController::edit()'];
        }

        return $container->privates['.service_locator.WDauLPg.App\\Controller\\SourceController::edit()'] = $a->withContext('App\\Controller\\SourceController::edit()', $container);
    }
}
