<?php

namespace ContainerI1Luur3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WDauLPgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WDauLPg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WDauLPg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'source' => ['privates', '.errored..service_locator.WDauLPg.App\\Entity\\Source', NULL, 'Cannot autowire service ".service_locator.WDauLPg": it needs an instance of "App\\Entity\\Source" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'source' => 'App\\Entity\\Source',
            'entityManager' => '?',
        ]);
    }
}
