<?php

namespace ContainerI1Luur3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored__ServiceLocator_CDRr68t_DateTimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cDRr68t.DateTime' shared service.
     *
     * @return \DateTime
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.cDRr68t": it references class "DateTime" but no such service exists.');
    }
}
