<?php

namespace ContainerI1Luur3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocumentControllerindexJsonService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SOia4js.App\Controller\DocumentController::index_json()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SOia4js.App\\Controller\\DocumentController::index_json()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'serializer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', false],
            'documentRepository' => ['privates', 'App\\Repository\\DocumentRepository', 'getDocumentRepositoryService', true],
        ], [
            'serializer' => '?',
            'documentRepository' => 'App\\Repository\\DocumentRepository',
        ]))->withContext('App\\Controller\\DocumentController::index_json()', $container);
    }
}
