<?php

namespace ContainerI1Luur3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocumentControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6YfNnC6.App\Controller\DocumentController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6YfNnC6.App\\Controller\\DocumentController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'documentRepository' => ['privates', 'App\\Repository\\DocumentRepository', 'getDocumentRepositoryService', true],
            'sourceService' => ['privates', 'App\\Service\\SourceService', 'getSourceServiceService', true],
        ], [
            'documentRepository' => 'App\\Repository\\DocumentRepository',
            'sourceService' => 'App\\Service\\SourceService',
        ]))->withContext('App\\Controller\\DocumentController::index()', $container);
    }
}
