<?php

namespace ContainerI1Luur3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSourceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.WDauLPg.App\Entity\Source' shared service.
     *
     * @return \App\Entity\Source
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.WDauLPg": it needs an instance of "App\\Entity\\Source" but this type has been excluded in "config/services.yaml".');
    }
}
