<?php

namespace ContainerI1Luur3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScheduledCommandsetLastExecutionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cDRr68t.Dukecity\CommandSchedulerBundle\Entity\ScheduledCommand::setLastExecution()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cDRr68t.Dukecity\\CommandSchedulerBundle\\Entity\\ScheduledCommand::setLastExecution()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lastExecution' => ['privates', '.errored..service_locator.cDRr68t.DateTime', NULL, 'Cannot autowire service ".service_locator.cDRr68t": it references class "DateTime" but no such service exists.'],
        ], [
            'lastExecution' => 'DateTime',
        ]))->withContext('Dukecity\\CommandSchedulerBundle\\Entity\\ScheduledCommand::setLastExecution()', $container);
    }
}
