<?php

namespace ContainerI1Luur3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSourceLevelService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SKCHlbO.App\Entity\SourceLevel' shared service.
     *
     * @return \App\Entity\SourceLevel
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.SKCHlbO": it needs an instance of "App\\Entity\\SourceLevel" but this type has been excluded in "config/services.yaml".');
    }
}
