<?php

namespace ContainerI1Luur3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSourceServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SourceService' shared autowired service.
     *
     * @return \App\Service\SourceService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/SourceService.php';

        return $container->privates['App\\Service\\SourceService'] = new \App\Service\SourceService(($container->privates['App\\Repository\\SourceRepository'] ?? $container->load('getSourceRepositoryService')));
    }
}
