<?php

namespace ContainerI1Luur3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSourceControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rP06vd5.App\Controller\SourceController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rP06vd5.App\\Controller\\SourceController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sourceRepository' => ['privates', 'App\\Repository\\SourceRepository', 'getSourceRepositoryService', true],
        ], [
            'sourceRepository' => 'App\\Repository\\SourceRepository',
        ]))->withContext('App\\Controller\\SourceController::index()', $container);
    }
}
