<?php

namespace ContainerI1Luur3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSourceLevelControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Sbr1ElV.App\Controller\SourceLevelController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Sbr1ElV.App\\Controller\\SourceLevelController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sourceLevelRepository' => ['privates', 'App\\Repository\\SourceLevelRepository', 'getSourceLevelRepositoryService', true],
        ], [
            'sourceLevelRepository' => 'App\\Repository\\SourceLevelRepository',
        ]))->withContext('App\\Controller\\SourceLevelController::index()', $container);
    }
}
