<?php

namespace ContainerI1Luur3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Dukecity\CommandSchedulerBundle\Command\TestCommand' shared autowired service.
     *
     * @return \Dukecity\CommandSchedulerBundle\Command\TestCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/dukecity/command-scheduler-bundle/Command/TestCommand.php';

        $container->services['Dukecity\\CommandSchedulerBundle\\Command\\TestCommand'] = $instance = new \Dukecity\CommandSchedulerBundle\Command\TestCommand();

        $instance->setName('scheduler:test');
        $instance->setHidden(true);
        $instance->setDescription('long running command');

        return $instance;
    }
}
