<?php

namespace ContainerI1Luur3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWaitDatabaseCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\WaitDatabaseCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\WaitDatabaseCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('db:wait', [], 'Waits for database availability.', false, #[\Closure(name: 'App\\Command\\WaitDatabaseCommand')] fn (): \App\Command\WaitDatabaseCommand => ($container->privates['App\\Command\\WaitDatabaseCommand'] ?? $container->load('getWaitDatabaseCommandService')));
    }
}
