<?php

namespace ContainerI1Luur3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getXmlReaderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\XmlReader' shared autowired service.
     *
     * @return \App\Service\XmlReader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/XmlReader.php';

        return $container->services['App\\Service\\XmlReader'] = new \App\Service\XmlReader();
    }
}
