INSERT INTO source (name, url, level_id) VALUES
('antena3', 'https://www.antena3.com/noticias/rss/4013050.xml', 2),
('abc', 'https://www.abc.es/rss/2.0/portada/', 2),
('lasexta', 'https://www.lasexta.com/rss/351410.xml', 1),
('lavanguardia', 'https://www.lavanguardia.com/rss/home.xml', 3),
('elpais', 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada', 1),
('elperiodico', 'https://www.elperiodico.com/es/rss/rss_portada.xml', 1),
('elmundo', 'https://e00-elmundo.uecdn.es/elmundo/rss/portada.xml', 2),
('periodistadigital', 'https://www.periodistadigital.com/feed/', 2),
('libertaddigital', 'https://feeds2.feedburner.com/libertaddigital/portada', 2),
('20minutos', 'https://www.20minutos.es/rss/', 3),
('hoy', 'https://www.hoy.es/rss/2.0/portada/', 3),
('expansion', 'https://e00-expansion.uecdn.es/rss/portada.xml', 2),
('elcorreo', 'https://www.elcorreo.com/rss/2.0/portada/', 3),
('eldiariomontanes', 'https://www.eldiariomontanes.es/rss/2.0/portada/', 3);
